name: dart_base_component
description: BaseComponent is a class that encapsulates logic for working with HTML, designed for a simple app to test integration with the Dart language.
version: 1.0.0
repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.6
  lints: ^2.0.0
